{ ... }: {
  imports = [
    ./gc.nix
    ./boot-loader.nix
    ./experimental-features.nix 
    ./fonts.nix
    ./gpg.nix
    ./home-manager.nix
    ./kernel.nix
    ./locale.nix
    ./mount-nas.nix
    ./nixpkgs-unfree.nix
    ./printing.nix
    ./nixos-config-rebuilder.nix
    ./sops.nix
    ./ssh.nix
    ./steam.nix
    ./system-packages.nix
    ./system-state.nix
    ./wayland.nix
    ./zram.nix
    ./zsh.nix
    ./wireguard.nix
    ./wheel.nix
    ./llama-swap.nix
    ./sunshine.nix
    ./dbus.nix
    ./avahi.nix
    ./flatpak.nix
    ./ollama.nix
    ./syncthing.nix
    ./plasma.nix
    ./sddm.nix
    ./xdg-portal.nix
    ./kde-patch.nix
  ];
}
