{ ... }: {
  imports = [
    ./services/_.nix
    ../gc.nix
    ./kde/_.nix 
    ./audio.nix                 
    ./bluetooth.nix
    ./boot-loader.nix
    ./experimental-features.nix 
    ./fonts.nix                 
    ./gpg.nix                   
    ./home-manager.nix          
    ./kernel.nix                
    ./locale.nix                
    ./mount-nas.nix                   
    ./networking.nix            
    ./nixpkgs-unfree.nix        
    ./printing.nix             
    ./rclone-sync.nix
    ./nixos-config-rebuilder.nix
    ./sops.nix                  
    ./ssh.nix                   
    ./steam.nix
    ./system-packages.nix       
    ./system-state.nix          
    ./touchpad.nix              
    ./wayland.nix              
    ./zram.nix
    ./zsh.nix                   
    ./wireguard.nix
  ];
}
