{ ... }: {
  imports = [
    ../gc.nix
    ./kde/_.nix 
    ./audio.nix                 
    ./avahi.nix
    ./bluetooth.nix
    ./boot-loader.nix
    ./dbus.nix
    ./experimental-features.nix 
    ./fonts.nix                 
    ./gpg.nix                   
    ./home-manager.nix          
    ./kde-pim.nix
    ./kernel.nix                
    ./locale.nix                
    ./mount-nas.nix                   
    ./networking.nix            
    ./nixpkgs-unfree.nix        
    ./printing.nix             
    ./rclone-sync.nix
    ./service-llama-swap.nix
    ./service-nixos-config-rebuilder.nix
    ./sops.nix                  
    ./ssh.nix                   
    ./steam.nix
    ./sunshine.nix
    ./system-packages.nix       
    ./system-state.nix          
    ./touchpad.nix              
    ./wayland.nix              
    ./zram.nix
    ./zsh.nix                   
  ];
}
